### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ZinuoCai** [jackbrookes/batch-ppt-to-pdf#2]
When I run your code, I meet an error:
```
Traceback (most recent call last):
  File "convert.py", line 24, in <module>
    powerpoint = init_powerpoint()
  File "convert.py", line 5, in init_powerpoint
    powerpoint = comtypes.client.CreateObject("Powerpoint.Application")
  File "D:\software\Anaconda\envs\MCM\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "D:\software\Anaconda\envs\MCM\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "D:\software\Anaconda\envs\MCM\lib\site-packages\comtypes\client\__init__.py", line 112, in GetBestInterface
    interface = getattr(mod, itf_name)
AttributeError: module 'comtypes.gen.PowerPoint' has no attribute '_Application'
```
The solution to this problem is change the method **init_powerpoint** to:
```
def init_powerpoint():
    powerpoint = win32com.client.DispatchEx("Powerpoint.Application")
    return powerpoint
```

**Comment by edehouck** [comment]
~~I have the same issue but the proposed workaround doesn't seem to work either. Could you describe it a bit more? Thanks in advance!~~
Edit: I simply forgot to import win32com.client. Thanks for the workaround!
